name: onyxite-customs-tool
version: '20190209'
github: mtolly/onyxite-customs
author: Michael Tolly <miketolly@gmail.com>
category: Distribution
license: GPL-3
license-file: LICENSE.txt

extra-source-files:
- vendors/Pentatonic.ttf
- vendors/VeraMono.ttf
- vendors/KV.bin
- vendors/rb3.png
- vendors/empty.milo_xbox
- vendors/empty-rb2.milo_xbox
- vendors/empty-rb2_weights.bin
- vendors/missing_song_data.dta
- vendors/rockband_drums.png
- vendors/rockband_guitarbass.png
- vendors/rockband_ghl.png
- ../player/www/index.html
- ../player/www/style.css
- ../player/www/app.min.js
- ../player/www/customize.js
- ../player/www/VarelaRound-Regular.ttf
- ../player/www/images/*.png
- cbits/*.h
- icon/icon.*

ghc-options: -Wall

library:

  source-dirs: src
  dependencies:
  - base
  - shake >= 0.16 && < 0.17
  - hashable
  - directory
  - temporary
  - aeson
  - text
  - unordered-containers
  - filepath
  - yaml
  - file-embed
  - event-list
  - non-negative
  - midi
  - hmidi
  - containers
  - bytestring
  - process >= 1.2.0.0 && < 1.7
  - resourcet
  - hsndfile
  - JuicyPixels >= 3.2.3.1
  - conduit
  - vector
  - transformers >= 0.5
  - mtl
  - extra
  - pureMD5
  - binary
  - array
  - base64-bytestring
  - pretty
  - monad-loops
  - time
  - ini
  - executable-path
  - split
  - data-default-class
  - utility-ht >= 0.0.1 && < 0.1
  - scientific
  - template-haskell
  - MonadRandom
  - data-binary-ieee754 >= 0.4.4 && < 0.5
  - zip-archive
  - silently
  - codec
  - deepseq
  - process-extras
  - path
  - path-io
  - exceptions
  - stm
  - mmorph
  - async
  - StateVar
  - req
  - profunctors
  - cryptonite
  - memory
  - unliftio-core
  - xml
  - zlib
  # my libraries:
  - jammittools >= 0.5.0.3 && < 0.6
  - midi-util >= 0.2 && < 0.3
  - conduit-audio >= 0.2 && < 0.3
  - conduit-audio-sndfile
  - conduit-audio-samplerate
  - conduit-audio-lame
  - conduit-audio-mpg123
  - rubberband >= 0.1.0.2 && < 0.2
  - tinyfiledialogs
  - JuicyPixels-stbir
  - ArkTool

  ghc-options: -O
  build-tools:
  - c2hs >= 0.27.1
  - alex
  - happy

  include-dirs:
  - cbits/
  c-sources:
  - cbits/stb_dxt.c
  - cbits/encode_vag.c
  extra-libraries:
  - stdc++

  when:
  - condition: os(mingw32)
    then:
      extra-libraries: shell32
      cpp-options: -DWINDOWS
      c-sources: cbits/winfiles.c
      dependencies: Win32
    else:
      dependencies: mountpoints
  - condition: os(darwin)
    cpp-options: -DMACOSX
    c-sources: cbits/macfiles.m
    frameworks: AppKit

executables:

  onyx:
    source-dirs: src-exe
    main: Main.hs

    # TODO a bunch of these can be trimmed down
    dependencies:
    - base
    - shake >= 0.16 && < 0.17
    - hashable
    - directory
    - temporary
    - aeson
    - text
    - unordered-containers
    - filepath
    - yaml
    - file-embed
    - event-list
    - non-negative
    - midi
    - hmidi
    - containers
    - bytestring
    - process >= 1.2.0.0 && < 1.7
    - resourcet
    - hsndfile
    - JuicyPixels >= 3.2.3.1
    - conduit
    - vector
    - transformers >= 0.5
    - mtl
    - extra
    - pureMD5
    - binary
    - array
    - base64-bytestring
    - pretty
    - monad-loops
    - time
    - ini
    - executable-path
    - split
    - data-default-class
    - utility-ht >= 0.0.1 && < 0.1
    - scientific
    - template-haskell
    - MonadRandom
    - data-binary-ieee754 >= 0.4.4 && < 0.5
    - zip-archive
    - silently
    - codec
    - deepseq
    - process-extras
    - path
    - path-io
    - exceptions
    - stm
    - mmorph
    - async
    - StateVar
    - req
    - profunctors
    - cryptonite
    - memory
    - unliftio-core
    - xml
    - zlib
    - fltkhs
    # my libraries:
    - jammittools >= 0.5.0.3 && < 0.6
    - midi-util >= 0.2 && < 0.3
    - conduit-audio >= 0.2 && < 0.3
    - conduit-audio-sndfile
    - conduit-audio-samplerate
    - conduit-audio-lame
    - conduit-audio-mpg123
    - rubberband >= 0.1.0.2 && < 0.2
    - tinyfiledialogs
    - JuicyPixels-stbir
    - ArkTool
    # the lib in this package
    - onyxite-customs-tool

    ghc-options: -threaded -O

    when:
    - condition: os(mingw32)
      then:
        cpp-options: -DWINDOWS
        ld-options: icon/icon.o -mwindows
      else:
        dependencies: mountpoints
    - condition: os(darwin)
      then:
        cpp-options: -DMACOSX
        ld-options: -lto_library
        # ^ this fixes C++ exception catching on mac.
        # see https://ghc.haskell.org/trac/ghc/ticket/11829
        extra-libraries:
        - fltkc # TODO breaks ghci
      else:
        # copied from fltkhs-hello-world
        ghc-options: '-pgml g++ "-optl-Wl,--allow-multiple-definition" "-optl-Wl,--whole-archive" "-optl-Wl,-Bstatic" "-optl-Wl,-lfltkc" "-optl-Wl,-Bdynamic" "-optl-Wl,--no-whole-archive"'

  onyx-package:
    main: Installer.hs
    dependencies: [base, nsis, text]
