packages:
- '.'
- location: XboxInternals/
  extra-dep: true
- location:
    git: git://github.com/mtolly/midi
    commit: fb36e91cbeaf3501342cb9c010ccb15647f7c3c2
  extra-dep: true
- location:
    git: git://github.com/mtolly/tinyfiledialogs
    commit: 0012e8e2b341350a30cbd0e4bc765b431e3061a0
  extra-dep: true
# following 2 are for windows SDL_MAIN fix
- location:
    git: git://github.com/haskell-game/sdl2
    commit: 9ba093763aa1d1cacb471631b91d289b91bfd646
  extra-dep: true
- location:
    git: git://github.com/haskell-game/sdl2-ttf
    commit: 71eeb468baf745bcf5ef392a5e713346a6cc168a
  extra-dep: true
extra-deps:
- conduit-audio-0.2.0.2
- conduit-audio-lame-0.1.2
- conduit-audio-samplerate-0.1.0.2
- conduit-audio-sndfile-0.1.2
- event-list-0.1.1.3
- explicit-exception-0.1.8
- jammittools-0.5.3
- midi-0.2.2.1
- midi-util-0.2
- non-negative-0.1.1
- monoid-transformer-0.0.3
- sdl2-ttf-1.0.0
- rubberband-0.1.0.2
- codec-0.2.1
resolver: lts-8.0
