packages:
- '.'
- '3d/'
- 'src-exe/'
- 'ffmpeg-binding/'
- 'simple-handle/'
extra-deps:
- conduit-audio-0.2.0.3
- conduit-audio-lame-0.1.2.1
- conduit-audio-samplerate-0.1.0.3
- conduit-audio-sndfile-0.1.2.2
- jammittools-0.5.5.2
- rubberband-0.1.0.2
- tinyfiledialogs-0.2.0.0
- JuicyPixels-3.3.7 # fixes a jpeg crash: https://github.com/Twinside/Juicy.Pixels/issues/205
- JuicyPixels-stbir-0.1.0.0
- hsndfile-vector-0.5.2
- wavefront-0.7.1.4
- tcp-streams-1.0.1.1
- caerbannog-0.6.1.1
- hashable-1.3.4.1 # fixes hash clash on windows: https://github.com/haskell-unordered-containers/hashable/pull/213
- RtMidi-0.5.0.1
- cryptohash-sha1-0.11.101.0
- language-c-0.9.1
# local folders
- game/
- ArkTool/
- kakasi/
- gamecube-dsp/
- ww2ogg/
- make_npdata/
- rb1-mogg-encrypt/
- cabal/Cabal/ # this submodule should just be a git reference, but stack appears to not apply it correctly that way
# git repos
- git: https://github.com/mtolly/midi
  commit: 66a49fe08bd941322061fc812f0eab6bac68c6f9
- git: https://github.com/mtolly/conduit-audio
  commit: 0a90a9541b261583a09e5d5f9f416bc7ae59d07d
  subdirs:
  - conduit-audio-mpg123
- git: https://github.com/mtolly/fltkhs
  # from TheGreatConsolidation upstream branch with several edits:
  # - updated fltk due to file picker bug in macos monterey
  # - fix some bindings on all platforms due to that update
  # - add some screen scale function bindings
  # - put built fltk and c-lib under onyx's .stack-work, instead of /tmp
  # - newer fltk also supports kdialog but I disabled that until it's more polished
  commit: b141c8098e89b9be30244c068e7fefd302f4c5db
  subdirs:
  - fltkhs
- git: https://github.com/mtolly/midi-util
  commit: 1ea0f72a3795375e4b9eafcaef2500d105faf20f
- git: https://github.com/mtolly/OpenAL
  commit: 3c74c9807c2d126cbbd2596082f9b9345a247ec5
- git: https://github.com/mtolly/codec # ghc 8.8 patch
  commit: 7415d2224135574fafaec533b7507e4276dd7c70
- git: https://github.com/mtolly/mpg123-haskell-binding
  commit: 4790b92549b7db51801a67cf1055259e3abcf60e
- git: https://github.com/kaoskorobase/hsndfile # unreleased past 0.8.0, switches to pkg-config
  commit: f532a1fdf119a543d7db20fe21f11ced5cffbb21
# - git: https://github.com/mtolly/cabal # patch to work around c2hs failing on Windows in onyxite-customs-lib, due to many repeated include dirs in its invocation
#   commit: 8b3141e6bc82b1d381674145868429e558c1cd5d
#   subdirs:
#   - Cabal
resolver: lts-17.12
flags:
  fltkhs:
    bundled: true
    opengl: true
allow-newer: true
