packages:
- '.'
- 'src-exe/'
- 'ffmpeg-binding/'
- 'simple-handle/'
extra-deps:
- conduit-audio-0.2.0.3
- conduit-audio-lame-0.1.2.1
- conduit-audio-samplerate-0.1.0.3
- conduit-audio-sndfile-0.1.2.2
- jammittools-0.5.5.2
- rubberband-0.1.0.2
- tinyfiledialogs-0.2.0.0
- JuicyPixels-stbir-0.1.0.0
- hsndfile-0.8.0
- hsndfile-vector-0.5.2
- wavefront-0.7.1.4
- tcp-streams-1.0.1.1
- caerbannog-0.6.0.5
# local folders
- game/
- 3d/
- ArkTool/
- kakasi/
- gamecube-dsp/
- ww2ogg/
# git repos
- git: git://github.com/mtolly/midi
  commit: 66a49fe08bd941322061fc812f0eab6bac68c6f9
- git: git://github.com/mtolly/conduit-audio
  commit: 0a90a9541b261583a09e5d5f9f416bc7ae59d07d
  subdirs:
  - conduit-audio-mpg123
- git: git://github.com/deech/fltkhs
  commit: 272d225e641e9b6161df82066e9a4b919c0e812a
  subdirs:
  - fltkhs
- git: git://github.com/mtolly/midi-util
  commit: 1ea0f72a3795375e4b9eafcaef2500d105faf20f
- git: git://github.com/mtolly/OpenAL
  commit: 3c74c9807c2d126cbbd2596082f9b9345a247ec5
- git: git://github.com/mtolly/codec # ghc 8.8 patch
  commit: 7415d2224135574fafaec533b7507e4276dd7c70
- git: git://github.com/mtolly/mpg123-haskell-binding
  commit: 4790b92549b7db51801a67cf1055259e3abcf60e
- git: git://github.com/mtolly/language-c
  commit: 5e40d962fb71b7e1256ff607194c53544709e761
resolver: lts-17.12
flags:
  fltkhs:
    bundled: true
    opengl: true
allow-newer: true
