packages:
- '.'
- 'src-exe/'
extra-deps:
- conduit-audio-0.2.0.3
- conduit-audio-lame-0.1.2.1
- conduit-audio-samplerate-0.1.0.3
- conduit-audio-sndfile-0.1.2.2
- jammittools-0.5.5.2
- rubberband-0.1.0.2
- tinyfiledialogs-0.2.0.0
- hmidi-0.2.2.1
- JuicyPixels-stbir-0.1.0.0
- hsndfile-0.8.0
- hsndfile-vector-0.5.2
- wavefront-0.7.1.3
# local folders
- game/
- 3d/
- ArkTool/
- kakasi/
- gamecube-dsp/
# git repos
- git: git://github.com/mtolly/midi
  commit: 66a49fe08bd941322061fc812f0eab6bac68c6f9
- git: git://github.com/mtolly/conduit-audio
  commit: 0a90a9541b261583a09e5d5f9f416bc7ae59d07d
  subdirs:
  - conduit-audio-mpg123
- git: git://github.com/deech/fltkhs
  commit: a46f5f752782624b1747b4d242ab677fabbcfadf
- git: git://github.com/mtolly/midi-util
  commit: 12951b7bc64cb006fa153d54b90174f0a90ba0f9
- git: git://github.com/mtolly/OpenAL
  commit: 3c74c9807c2d126cbbd2596082f9b9345a247ec5
- git: git://github.com/mtolly/mpg123-haskell-binding
  commit: 4790b92549b7db51801a67cf1055259e3abcf60e
resolver: lts-14.27
flags:
  fltkhs:
    bundled: true
    opengl: true
    demos: false
