packages:
- '.'
- location: ArkTool/
  extra-dep: true
- location: XboxInternals/
  extra-dep: true
- location:
    git: git://github.com/mtolly/midi
    commit: 183a57f18c9e2d89497451530843b49cc6111919
  extra-dep: true
- location:
    git: git://github.com/mtolly/JuicyPixels-stbir
    commit: 5fe4d64d07d28f34d70cd1fc6ccaf634e33f467f
  extra-dep: true
# following 2 are for windows SDL_MAIN fix
- location:
    git: git://github.com/haskell-game/sdl2
    commit: 9ba093763aa1d1cacb471631b91d289b91bfd646
  extra-dep: true
- location:
    git: git://github.com/haskell-game/sdl2-ttf
    commit: 71eeb468baf745bcf5ef392a5e713346a6cc168a
  extra-dep: true
extra-deps:
- conduit-audio-0.2.0.3
- conduit-audio-lame-0.1.2.1
- conduit-audio-samplerate-0.1.0.3
- conduit-audio-sndfile-0.1.2.1
- jammittools-0.5.3.2
- midi-util-0.2
- rubberband-0.1.0.2
- tinyfiledialogs-0.2.0.0
resolver: nightly-2017-12-30
