packages:
- packages/onyx-lib
- packages/onyx-lib-game
- packages/onyx-exe-toolkit
- packages/onyx-ffmpeg
- packages/onyx-handle
extra-deps:
- conduit-audio-0.2.0.3
- conduit-audio-lame-0.1.2.1
- conduit-audio-samplerate-0.1.0.3
- conduit-audio-sndfile-0.1.2.2
- jammittools-0.5.5.2
- rubberband-0.1.0.2
- tinyfiledialogs-0.2.0.0
- JuicyPixels-stbir-0.1.0.0
- wavefront-0.7.1.4
- caerbannog-1.0.0.2
- RtMidi-0.5.0.2
# local folders
- packages/onyx-arktool
- packages/onyx-kakasi
- packages/onyx-gamecube-dsp
- packages/onyx-wwise
- packages/onyx-npdata
- packages/onyx-mogg-encrypt
- packages/onyx-autochart
- cabal/Cabal/ # this submodule should just be a git reference, but stack appears to not apply it correctly that way
# git repos
- git: https://github.com/mtolly/midi
  commit: 67c595a8f0c3b2fa193c088374de5bf544234ff0 # string-param branch
- git: https://github.com/mtolly/conduit-audio
  commit: 0a90a9541b261583a09e5d5f9f416bc7ae59d07d
  subdirs:
  - conduit-audio-mpg123
- git: https://github.com/mtolly/fltkhs
  # from TheGreatConsolidation upstream branch with several edits:
  # - updated fltk due to file picker bug in macos monterey
  # - fix some bindings on all platforms due to that update
  # - add some screen scale function bindings
  # - put built fltk and c-lib under onyx's .stack-work, instead of /tmp
  # - newer fltk also supports kdialog but I disabled that until it's more polished
  commit: b141c8098e89b9be30244c068e7fefd302f4c5db
  subdirs:
  - fltkhs
- git: https://github.com/mtolly/midi-util
  commit: e58affa31251cec0d50f9b0588acfa514edd58ae # string-param branch
- git: https://github.com/mtolly/OpenAL
  commit: 3c74c9807c2d126cbbd2596082f9b9345a247ec5
- git: https://github.com/mtolly/codec # ghc 8.8+ and aeson patches
  commit: 7aedc9534afb996cb11a557eeadc74462e49e8de
- git: https://github.com/mtolly/mpg123-haskell-binding
  commit: 4790b92549b7db51801a67cf1055259e3abcf60e
- git: https://github.com/kaoskorobase/hsndfile # unreleased past 0.8.0, switches to pkg-config
  commit: f532a1fdf119a543d7db20fe21f11ced5cffbb21
# - git: https://github.com/mtolly/cabal # patch to work around c2hs failing on Windows in onyxite-customs-lib, due to many repeated include dirs in its invocation
#   commit: f91d35bfdab221b2b6102cf462811994b836c23e
#   subdirs:
#   - Cabal
- git: https://github.com/mtolly/shake # disables shake controlling the thread count
  commit: a4ecb069cbce6d4566e2dd025bcc79b8f8a5839d
resolver: nightly-2022-09-17
flags:
  fltkhs:
    bundled: true
    opengl: true
allow-newer: true
