packages:
- 'build'
- location: build/resources
  extra-dep: true
- location: dta
  extra-dep: true
- location: parse
  extra-dep: true
- location: stack-trace
  extra-dep: true
- location: display
  extra-dep: true
- location: midiscript
  extra-dep: true
- location:
    git: git://github.com/mtolly/midi
    commit: b6249df44ddfbd342acbb099cbc4ef760df13bcf
  extra-dep: true
extra-deps:
- conduit-audio-0.2.0.2
- conduit-audio-lame-0.1.2
- conduit-audio-samplerate-0.1.0.2
- conduit-audio-sndfile-0.1.2
- event-list-0.1.1.3
- jammittools-0.5.0.3
- midi-0.2.2.1
- midi-util-0.2
- non-negative-0.1.1
- monoid-transformer-0.0.3
resolver: nightly-2016-06-17
