packages:
- 'build'
- 'build/resources'
- 'dta'
- 'parse'
- 'stack-trace'
- 'display'
- 'editor'
- location:
    git: git@github.com:Twinside/Juicy.Pixels
    commit: 209e9ae2ad77482a2556fd5aba8082c8580ce725
  extra-dep: true
extra-deps:
- conduit-audio-0.2.0.1
- conduit-audio-samplerate-0.1.0.1
- conduit-audio-sndfile-0.1.1
- conduit-audio-lame-0.1.1
- jammittools-0.5.0.2
- midi-0.2.1.5
- midi-util-0.1.1.1
- sdl2-2.1.0
- HPDF-1.4.8
- event-list-0.1.1.2
- explicit-exception-0.1.7.3
- hsndfile-0.8.0
- hsndfile-vector-0.5.2
- monoid-transformer-0.0.3
- non-negative-0.1.1
- utility-ht-0.0.11
- vector-0.10.12.3
resolver: lts-4.0
