packages:
- '.'
- location: game/
  extra-dep: true
- location: ArkTool/
  extra-dep: true
- location: kakasi/
  extra-dep: true
- location:
    git: git://github.com/mtolly/midi
    commit: 28866f4715cde594d8d8ec5e6f3beecb64783614
  extra-dep: true
- location:
    git: git://github.com/mtolly/conduit-audio
    commit: e32b257121dcfa55c8bf8e3c6ba5a0d23dcb0fc3
    subdirs:
    - conduit-audio-mpg123
  extra-dep: true
- location:
    git: git://github.com/deech/fltkhs
    commit: c55aa9198088198e83060276114fcb8087872734
  extra-dep: true
extra-deps:
- conduit-audio-0.2.0.3
- conduit-audio-lame-0.1.2.1
- conduit-audio-samplerate-0.1.0.3
- conduit-audio-sndfile-0.1.2.1
- jammittools-0.5.5.2
- midi-util-0.2.1
- rubberband-0.1.0.2
- tinyfiledialogs-0.2.0.0
- hmidi-0.2.2.1
- mpg123-bindings-0.1.0.0
- JuicyPixels-stbir-0.1.0.0
- hsndfile-0.8.0
- hsndfile-vector-0.5.2
resolver: nightly-2019-04-12
flags:
  fltkhs:
    bundled: true
