packages:
- '.'
- 'src-exe/'
extra-deps:
- conduit-audio-0.2.0.3
- conduit-audio-lame-0.1.2.1
- conduit-audio-samplerate-0.1.0.3
- conduit-audio-sndfile-0.1.2.1
- jammittools-0.5.5.2
- rubberband-0.1.0.2
- tinyfiledialogs-0.2.0.0
- hmidi-0.2.2.1
- mpg123-bindings-0.1.0.0
- JuicyPixels-stbir-0.1.0.0
- hsndfile-0.8.0
- hsndfile-vector-0.5.2
# local folders
- game/
- 3d/
- ArkTool/
- kakasi/
- gamecube-dsp/
# git repos
- git: git://github.com/mtolly/midi
  commit: 28866f4715cde594d8d8ec5e6f3beecb64783614
- git: git://github.com/mtolly/conduit-audio
  commit: e32b257121dcfa55c8bf8e3c6ba5a0d23dcb0fc3
  subdirs:
  - conduit-audio-mpg123
- git: git://github.com/deech/fltkhs
  commit: c55aa9198088198e83060276114fcb8087872734
- git: git://github.com/mtolly/midi-util
  commit: 12951b7bc64cb006fa153d54b90174f0a90ba0f9
resolver: nightly-2019-09-21
flags:
  fltkhs:
    bundled: true
