packages:
- 'build'
- 'build/resources'
- 'dta'
- 'parse'
- 'stack-trace'
- 'display'
extra-deps:
- conduit-audio-0.2.0.1
- conduit-audio-lame-0.1.1
- conduit-audio-samplerate-0.1.0.1
- conduit-audio-sndfile-0.1.1
- event-list-0.1.1.3
- jammittools-0.5.0.3
- lock-file-0.5.0.2
- midi-0.2.2
- midi-util-0.1.1.1
- non-negative-0.1.1
- tagged-exception-core-2.2.0.0
- monoid-transformer-0.0.3
resolver: lts-5.5
