packages:
- '.'
- location:
    git: git://github.com/mtolly/midi
    commit: fb36e91cbeaf3501342cb9c010ccb15647f7c3c2
  extra-dep: true
extra-deps:
- conduit-audio-0.2.0.2
- conduit-audio-lame-0.1.2
- conduit-audio-samplerate-0.1.0.2
- conduit-audio-sndfile-0.1.2
- event-list-0.1.1.3
- jammittools-0.5.0.3
- midi-0.2.2.1
- midi-util-0.2
- non-negative-0.1.1
- monoid-transformer-0.0.3
resolver: lts-7.10
