flags:
  onyxite-customs-preview:
    SDLDisplay: true
packages:
- 'build'
- 'build/resources'
- 'dta'
- 'parse'
- 'preview'
extra-deps:
- conduit-audio-0.2
- conduit-audio-samplerate-0.1
- conduit-audio-sndfile-0.1
- event-list-0.1.1.2
- hsndfile-0.7.1
- jammittools-0.5.0.2
- midi-0.2.1.5
- midi-util-0.1.1.1
- non-negative-0.1.1
- sdl2-image-0.1.3.2
- HPDF-1.4.8
- explicit-exception-0.1.7.3
- hsndfile-vector-0.5.2
- monoid-transformer-0.0.3
- utility-ht-0.0.11
resolver: lts-3.5
