language: haskell
ghc:
  - 7.8
install:
  - wget -q -O- https://s3.amazonaws.com/download.fpcomplete.com/ubuntu/fpco.key | sudo apt-key add -
  - echo 'deb http://download.fpcomplete.com/ubuntu/precise stable main' | sudo tee /etc/apt/sources.list.d/fpco.list
  - sudo apt-get update -qq
  - sudo apt-get install stack wine libsndfile-dev libsamplerate-dev -y
  - stack setup
  - stack install
env:
  - ONYXITE_MIN=0  ONYXITE_MAX=9999
script:
  - test/run
