name: onyxite-customs-tool
version: '20210213'
github: mtolly/onyxite-customs
author: Michael Tolly <miketolly@gmail.com>
category: Distribution
license: GPL-3
license-file: ../LICENSE.txt

extra-source-files:
- ../icon/icon.*

ghc-options: -Wall

executables:

  onyx:
    source-dirs: '.'
    main: Main.hs

    dependencies:
    - base
    - directory
    - aeson
    - text
    - bytestring
    - unordered-containers
    - filepath
    - yaml
    - process
    - resourcet
    - hsndfile
    - transformers
    - data-default-class
    - stm
    - req
    - fltkhs
    - midi
    - event-list
    - containers
    - time
    - non-negative
    - binary
    - tcp-streams
    - io-streams
    - fsnotify
    - gl
    - async
    - network
    - exceptions
    - extra
    - JuicyPixels
    # my libraries
    - midi-util
    - conduit-audio
    # local
    - onyxite-customs-lib
    - onyx-game-3d

    ghc-options: -threaded -O

    when:
    - condition: os(mingw32)
      then:
        cpp-options: -DWINDOWS
        ld-options: ../icon/icon.o -mwindows
        dependencies: Win32
      else:
        dependencies: mountpoints
    - condition: os(darwin)
      then:
        cpp-options: -DMACOSX
        # copied from fltkhs-hello-world, also unwind is to avoid https://gitlab.haskell.org/ghc/ghc/issues/11829
        ghc-options: "-optl-Wl,-lfltkc -optl-Wl,-keep_dwarf_unwind"
      else:
        # copied from fltkhs-hello-world
        ghc-options: '-pgml g++ "-optl-Wl,--allow-multiple-definition" "-optl-Wl,--whole-archive" "-optl-Wl,-Bstatic" "-optl-Wl,-lfltkc" "-optl-Wl,-Bdynamic" "-optl-Wl,--no-whole-archive"'

  onyx-package:
    main: ../Installer.hs
    dependencies: [base, nsis, text, process, containers, filepath, directory]
