flags:
  onyxite-customs-preview:
    SDLDisplay: true
packages:
- '.'
- ../parse
extra-deps:
- event-list-0.1.1.2
- midi-0.2.1.5
- midi-util-0.1.1.1
- non-negative-0.1.1
- sdl2-image-0.1.3.2
- explicit-exception-0.1.7.3
- monoid-transformer-0.0.3
- utility-ht-0.0.10
resolver: nightly-2015-06-28
