name: onyx-game-3d
version: '20190209'
github: mtolly/onyxite-customs
author: Michael Tolly <miketolly@gmail.com>
category: Distribution
license: GPL-3
license-file: ../LICENSE.txt

ghc-options: -Wall

library:

  source-dirs: src
  dependencies:
  - base
  - onyxite-customs-lib
  - containers
  - vector
  - async
  - temporary
  - filepath
  - resourcet
  - transformers
  - unordered-containers
  - event-list
  - midi-util
  - gl
  - JuicyPixels
  - bytestring
  - linear
  - text
  - non-negative
  - utility-ht
  - OpenAL
  - conduit
  - conduit-audio
  - conduit-audio-sndfile
  - wavefront
  - codec
  - directory
  build-tools:
  - c2hs
